FROM mysql:5.7

ADD my.cnf /etc/mysql/my.cnf

ARG MYSQL_DATABASE
ARG MYSQL_ROOT_PASSWORD
ARG MYSQL_PASSWORD

ENV MYSQL_ALLOW_EMPTY_PASSWORD="true"
ENV MYSQL_DATABASE=${MYSQL_DATABASE}
ENV MYSQL_PASSWORD=${MYSQL_PASSWORD}
ENV MYSQL_ROOT_PASSWORD=${MS_TEM}

EXPOSE 3306
